alias: away routine
trigger:
  - platform: state
    entity_id: person.paul
    to: "not_home"
    for: "00:20:00"
action:
  - service: light.turn_off
    data:
      entity_id: all
  - service: switch.turn_off
    data:
      entity_id: all
