alias: light off on backend on
trigger:
  platform: state
  entity_id: switch.desk_backend
  to: "on"
condition:
  - "{{ state_attr('sun.sun', 'elevation') > 5 }}"
action:
  - delay: "00:02:00"
  - service: light.turn_off
    entity_id:
      - light.shelf
      - light.desk
      - light.floor_lamp
      - light.bedlampje
