alias: Pauls phone is almost charged
trigger:
  - platform: numeric_state
    entity_id: sensor.pauls_phone_battery
    above: 75
action:
  - service: sonos.snapshot
    data:
        entity_id: all
        with_group: True

  - delay:
      seconds: 3
      
  - service: media_player.volume_set
    data:
      volume_level: 0.25
    target:
      entity_id: media_player.sonos_one
      
  - service: tts.google_translate_say
    data:
      entity_id: media_player.sonos_one
      message: Phone Charged
      
  - delay:
      seconds: 3

  - service: sonos.restore
    data:
        entity_id: all
        with_group: True