alias: Turn on docking station when vacuum is running
trigger:
  platform: state
  entity_id: vacuum.pauls_putze
  to: cleaning
action:
  - service: switch.turn_on
    target:
      entity_id: switch.desk_backend