alias: motion in hallway
mode: single
max_exceeded: silent
trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_hallway
condition:
  - "{{ states('sensor.illuminance_hallway') | int < 10 }}"
action:
  - choose:
      ### state is now on
      - conditions: >
          {{ states('binary_sensor.motion_sensor_hallway') == 'on' }}
        sequence:
          - choose:
              ### candle mode on
              - conditions: >
                  {{ states('input_boolean.candle_mode') == 'on' }}
                sequence:
                  - scene: scene.hallway_night
              ### nightlight
              - conditions: >
                  {{ states('sun.sun') == 'above_horizon' }}
                sequence:
                  - scene: scene.hallway_bright
              ### dimmed light
              - conditions: >
                  {{ states('sensor.illuminance_hallway') | int < 1000 }}
                sequence:
                  - scene: scene.hallway_dim
            ### bright light
            default:
              - scene: scene.hallway_night
          - wait_for_trigger:
              platform: state
              entity_id: binary_sensor.motion_sensor_hallway
              to: "off"
              for: "00:03:00"
          - scene: scene.hallway_off
